-- public.map_enum definition

-- Drop table

-- DROP TABLE public.map_enum;

CREATE TABLE map_enum
(
    id         int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    statusenum int4 NULL,
    CONSTRAINT map_enum_pkey PRIMARY KEY (id)
);


-- public.tbl_counter definition

-- Drop table

-- DROP TABLE public.tbl_counter;

CREATE TABLE tbl_counter
(
    id               varchar(255) NOT NULL,
    attack_on_titan  int4 NULL,
    demon_slayer     int4 NULL,
    dragon_ball      int4 NULL,
    my_hero_academia int4 NULL,
    naruto           int4         NOT NULL,
    one_piece        int4 NULL,
    sailor_moon      int4 NULL,
    studio_ghibli    int4 NULL,
    account          int4 NULL,
    prompt_detail    int4 NULL,
    tutorial         int4 NULL,
    figure_model     int4 NULL,
    key_chain        int4 NULL,
    sticker          int4 NULL,
    t_shirt          int4 NULL,
    CONSTRAINT tbl_counter_pkey PRIMARY KEY (id)
);